### ISSUE TITLE
Why does 2D UNET convert data to HDF5 when 3D UNET does not?

### ISSUE THREAD

**Issue by wxr521314** [IntelAI/unet#21]
Hi sjain-stanford ：
    Thanks for sharing your cod.I have three questions.
    1. Have you written any relevant papers?
    2. Why does 2D UNET convert data to HDF5 when 3D UNET does not?
    3.Are you using a GPU?  I see tensorFlow is a CPU version. If I want to use GPU, do I just need to install tensorFlow-GPU?

Best wish！

**Comment by tonyreina** [comment]
Sorry for the delay.

1. Yes. For example, https://downloads.dell.com/manuals/common/dellemc_overcoming_memory_bottleneck_ai_healthcare.pdf
2. I'm hoping to update the 2D U-Net to remove the HDF5 loader. I used that first because it was an easy dataloader at the time. When I moved to 3D U-Net, it made more sense just to define my own Python iterator.
3. I'm using a CPU, but yes you can use a GPU by simply installing the GPU version of TensorFlow.
